### ISSUE TITLE
create hong_fizzbuzz

### ISSUE THREAD

**Issue by efforter** [fastcampus-avengers/team-avengers#2]
## Description

fizzbuzz 기능 파일 python으로 만들기

## Tasks

- [x] fizz  구현
- [x] buzz  구현
- [x] fizzbuzz  구현

## References

BROCK, Kevin. The ‘FizzBuzz’programming test: A case-based exploration of rhetorical style in code. Computational Culture, 2016, 5.

**Comment by yes-yeseung** [comment]
Now GOOOD to go!!
